version: '3'

services:
  minio:
    image: minio/minio
    volumes:
      - minio-data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: test
    command: server /data
volumes:
  minio-data:
